"""Deterministic rules engine for fraud detection.

This module implements rule-based signals that complement ML predictions.
Rules generate structured signals that contribute to the overall risk assessment.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class RuleSignal:
    """Signal generated by a rule."""

    rule: str
    triggered: bool
    severity: str  # low, medium, high, critical
    score_contribution: float
    description: str


class RuleEngine:
    """Evaluate transaction against deterministic rules."""

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        self.config = config or {}
        self.rules = self._initialize_rules()

    def _initialize_rules(self) -> list[dict[str, Any]]:
        """Initialize rule configurations."""
        return [
            {
                "name": "new_device",
                "description": "Transaction from a new device",
                "severity": "high",
                "score_contribution": 20,
                "condition": lambda t: t.get("device_first_seen", False),
            },
            {
                "name": "amount_anomaly",
                "description": "Transaction amount significantly deviates from sender's average",
                "severity": "high",
                "score_contribution": 25,
                "condition": lambda t: abs(t.get("amount_zscore", 0)) > 2,
            },
            {
                "name": "high_amount_ratio",
                "description": "Transaction amount is much higher than sender's average",
                "severity": "medium",
                "score_contribution": 15,
                "condition": lambda t: t.get("amount_ratio_to_avg", 1) > 3,
            },
            {
                "name": "velocity_anomaly",
                "description": "High transaction velocity in recent period",
                "severity": "high",
                "score_contribution": 20,
                "condition": lambda t: t.get("transactions_last_1h", 0) > 10,
            },
            {
                "name": "high_risk_merchant",
                "description": "Transaction at a merchant with historically high fraud rate",
                "severity": "medium",
                "score_contribution": 15,
                "condition": lambda t: t.get("merchant_fraud_rate_prior", 0) > 0.1,
            },
            {
                "name": "high_risk_location",
                "description": "Transaction from a location with historically high fraud rate",
                "severity": "medium",
                "score_contribution": 15,
                "condition": lambda t: t.get("location_fraud_rate_prior", 0) > 0.1,
            },
            {
                "name": "first_transaction",
                "description": "First transaction from this sender",
                "severity": "low",
                "score_contribution": 10,
                "condition": lambda t: (
                    t.get("customer_transaction_count_prior", 0) == 0
                ),
            },
            {
                "name": "high_frequency_sender",
                "description": "Sender has very high transaction frequency",
                "severity": "medium",
                "score_contribution": 10,
                "condition": lambda t: t.get("customer_transactions_per_day", 0) > 20,
            },
        ]

    def evaluate(self, transaction: dict[str, Any]) -> list[RuleSignal]:
        """Evaluate a transaction against all rules.

        Args:
            transaction: Dictionary with transaction features.

        Returns:
            List of RuleSignal objects for triggered rules.
        """
        signals = []

        for rule in self.rules:
            try:
                triggered = rule["condition"](transaction)
                if triggered:
                    signals.append(
                        RuleSignal(
                            rule=rule["name"],
                            triggered=True,
                            severity=rule["severity"],
                            score_contribution=rule["score_contribution"],
                            description=rule["description"],
                        )
                    )
            except (KeyError, TypeError, ValueError):
                # Skip rule if features are missing
                continue

        return signals

    def get_total_rule_score(self, signals: list[RuleSignal]) -> float:
        """Calculate total score contribution from rules.

        Args:
            signals: List of triggered rule signals.

        Returns:
            Total score contribution (capped at 100).
        """
        total = sum(s.score_contribution for s in signals)
        return min(total, 100.0)

    def get_rule_summary(self, signals: list[RuleSignal]) -> dict[str, Any]:
        """Get a summary of triggered rules.

        Args:
            signals: List of triggered rule signals.

        Returns:
            Dictionary with rule summary.
        """
        return {
            "total_rules_triggered": len(signals),
            "total_score_contribution": self.get_total_rule_score(signals),
            "rules": [
                {
                    "rule": s.rule,
                    "severity": s.severity,
                    "score_contribution": s.score_contribution,
                    "description": s.description,
                }
                for s in signals
            ],
        }
